name = "astroweb-theme-ssr"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-07-20"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build"


[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true